"""creating blogpost model

Revision ID: 0183a58dfbf8
Revises: e4e0d5ee4ff4
Create Date: 2022-07-26 15:21:04.279619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0183a58dfbf8'
down_revision = 'e4e0d5ee4ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('body', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_post_title'), 'blog_post', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_post_title'), table_name='blog_post')
    op.drop_table('blog_post')
    # ### end Alembic commands ###
