"""create user model

Revision ID: c2414f1a5fff
Revises: d5d57f93aaa9
Create Date: 2022-07-17 17:39:21.438672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2414f1a5fff'
down_revision = 'd5d57f93aaa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogpost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogpost',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=80), nullable=True),
    sa.Column('headline', sa.VARCHAR(length=80), nullable=True),
    sa.Column('text', sa.VARCHAR(length=80), nullable=True),
    sa.Column('picture_url', sa.VARCHAR(length=260), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###
