"""add picture_url to Cookie

Revision ID: d83b6d274cc5
Revises: 59f58c5877be
Create Date: 2022-06-21 18:35:35.242531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83b6d274cc5'
down_revision = '59f58c5877be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cookie', sa.Column('picture_url', sa.String(length=260), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cookie', 'picture_url')
    # ### end Alembic commands ###
